services:
  redis-ai:
    image: redis:7
    container_name: redis-ai
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data

  needs-worker:
    build: .
    container_name: needs-worker
    entrypoint: ["python"]
    command: ["agents/need_worker.py"]
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - REDIS_HOST=redis-ai
      - REDIS_PORT=6379
    ports:
      - "9001:9001"
    depends_on:
      - redis-ai

  opportunity-agent:
    build: .
    container_name: opportunity-agent
    entrypoint: ["python"]
    command: ["agents/opportunity_agent.py"]
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - REDIS_HOST=redis-ai
      - REDIS_PORT=6379
    ports:
      - "9003:9003"
    depends_on:
      - redis-ai

  supplier-agent:
    build: .
    container_name: supplier-agent
    entrypoint: ["python"]
    command: ["agents/supplier_agent.py"]
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - REDIS_HOST=redis-ai
      - REDIS_PORT=6379
    ports:
      - "9005:9005"
    depends_on:
      - redis-ai

  merchant-agent:
    build: .
    container_name: merchant-agent
    entrypoint: ["python"]
    command: ["agents/merchant_agent.py"]
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - REDIS_HOST=redis-ai
      - REDIS_PORT=6379
    ports:
      - "9004:9004"
    depends_on:
      - redis-ai
      - supplier-agent
      - opportunity-agent

  match-agent:
    build: .
    container_name: match-agent
    entrypoint: ["python"]
    command: ["agents/match_agent.py"]
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - REDIS_HOST=redis-ai
      - REDIS_PORT=6379
    ports:
      - "9002:9002"
    depends_on:
      - redis-ai
      - needs-worker
      - opportunity-agent

  insight-agent:
    build: .
    container_name: insight-agent
    entrypoint: ["python"]
    command: ["agents/insight_agent.py"]
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - REDIS_HOST=redis-ai
      - REDIS_PORT=6379
    ports:
      - "9006:9006"
    depends_on:
      - match-agent

  dashboard:
    build: .
    container_name: dashboard
    entrypoint: ["streamlit"]
    command:
      - run
      - dashboard/streamlit_app.py
      - --server.port
      - "8501"
      - --server.address
      - "0.0.0.0"
      - --server.fileWatcherType
      - "none"
    volumes:
      - .:/app
    ports:
      - "8502:8501"
    environment:
      - REDIS_HOST=redis-ai
      - REDIS_PORT=6379
    depends_on:
      - redis-ai

volumes:
  redis-data: